<?php
    echo "<br>";
    echo "<br>";
    echo "<form method='post' action='' >";
        echo "<input type='hidden' name='thong_tin_khach_hang' value='co' > ";
        echo "<table>";
            echo "<tr>";
                echo "<td colspan='2' height='30px' >";
                    echo "<b>Thông tin mua hàng</b>";
                echo "</td>";
            echo "</tr>";

            echo "<tr>";
            echo"<br>";
                echo "<td height='40px' >Lưu ý : </td>";
                echo "<td>&nbsp";
                    echo "Tên người mua , địa chỉ , điện thoại bắt buộc phải điền vào";
                    echo "</td>";
                      echo "</tr>";
            echo "<tr>&nbsp";
                echo "<td width='180px' >Size giày của bạn :</td>";
                echo "<td>";
                    echo "<input type='number' min='37' max='45' style='width:100px ;height:30px' name='size_giay' >";
                echo "</td>";
            echo "</tr>";
            echo "<tr>&nbsp";
                echo "<td width='180px' >Tên người mua :</td>";
                echo "<td>";
                    echo "<input type='text' style='width:400px ;height:50px' name='ten_nguoi_mua' >";
                echo "</td>";
            echo "</tr>";
            echo "<tr>";
                echo "<td>Email : </td>";
                echo "<td>";
                    echo "<input type='text' style='width:400px;height:50px' name='email' >";
                echo "</td>";
            echo "</tr>";
            echo "<tr>";
                echo "<td>Địa chỉ : </td>";
                echo "<td>";
                    echo "<textarea style='width:400px;;height:50px' name='dia_chi' ></textarea>";
                echo "</td>";
            echo "</tr>";
            echo "<tr>";
                echo "<td>Điện thoại : </td>";
                echo"<br>";
                echo "<td>";
                    echo "<input type='text' style='width:400px;height:50px' name='dien_thoai' >";
                echo "</td>";
            echo "</tr>";
            echo "<tr>";
                echo "<td>Nội dung :</td>";
                echo "<td>";
                    echo "<textarea style='width:400px;height:200px' name='noi_dung' ></textarea>";
                echo "</td>";
            echo "</tr>";echo"<br>";
            echo "<tr>";
                echo "<td>&nbsp;</td>";
                echo "<td>";
                    echo "<input type='submit' value='Mua hàng' >";
                echo "</td>";
            echo "</tr>";
        echo "</table>";
    echo "</form>";
